// if you're reading this code, please don't look at all the splash messages here. it spoils the experience of finding new ones :)


window.splashes = [
    "Dukemz Gaming",
    "Any computer is a laptop if you're brave enough!",
    "Humans are basically cucumbers with anxiety.",
    "<a href='https://dukemz.github.io/posts/22/iamlivinginyourwalls/'>I am living in your walls.</a>",
    "🗿",
    "🦆",
    "🎷🦆",
    "░░░░░░░",
    "▓░░░░░░",
    "▓▓░░░░░",
    "▓▓▓░░░░",
    "▓▓▓▓░░░",
    "▓▓▓▓▓░░",
    "▓▓▓▓▓▓░", // lol it never loads
    "I forgor 💀",
    "Part of a complete breakfast!",
    "1 of your 5 a day!",
    "Batteries not included.",
    "No artificial flavours or preservatives.",
    "Not sold separately!",
    "doot doot",
    "I can't find the bug spray.",
    "This gradient is cool.",
    "Spreading positivity since 2018!",
    "This site uses biscuits... Technobiscuits.",
    "dukemz.",
    "dukemz?",
    "dukemz!",
    "dukemz,",
    "dukemz;",
    "dukemz:",
    "dukemz...",
    "dukemz~",
    "dukemz*",
    "Error on line 39: Could not think of a splash.",
    "Llama, llama, duck",
    "Potassium.",
    "plus9 when?",
    "The duck ate my homework.",
    "How do you pronounce scone?",
    "My house plant is going to die.",
    "INTERCONTINENTAL BALLISTIC PINEAPPLE!!!",
    "This message may appear.",
    "√(-1) love you!",
    "Cucumber still watches us.",
    "Fry an egg with your face!",
    "Menger sponge.",
    "Moss Habitat!",
    "webstuff | webstuff yee",
    "Are biscuits a currency?",
    "Hello world!",
    "XHESSRBIUSCEDOBTCPM™",
    "Chicken. 💥",
    "ALL OUR FOOD KEEPS BLOWING UP!",
    "🗿 (moai) is an emotion that cannot be described.",
    ":)",
    "Which came first, the egg or the egg?",
    "BirbOS 10 will never happen.",
    "At least it's better than Cars 2",
    "test peanut",
    "The ducks are coming for you.",
    "NovoBot is probably cancelled!",
    "You know what that means...",
    "PA-FISH",
    "Technologically advanced!",
    "<a href='https://youtu.be/0UWpTyuUxNo'>https://youtu.be/0UWpTyuUxNo</a>",
    "<a href='https://youtu.be/0UWpTyuUxNo'>Click for a microwave!</a>",
    "Dukemz Beanz - in stores now!",
    "Stop being reasonable, this is the internet",
    "I'm a potato.",
    "Aria Math!",
    "Can't count to 3!",
    "oh the missouri",
    "Hopefully not copyrighted!",
    "Not very original!",
    "There are 10 types of people.<br>Those who understand binary, and those who don't.",
    "Run from your refrigerator!",
    "Wash your hands!",
    "Due ewe no wart the thyme ears?",
    "Time flies like an arrow and fruit flies like a banana...",
    "I wasn't originally going to get a brain transplant...<br>but then I changed my mind.",
    "Buffalo buffalo Buffalo buffalo buffalo buffalo Buffalo buffalo.",
    "Let in some sun!",
    "Boss rush time!",
    "It's dangerous to go alone, take <a href='/img/duck.jpg'>this!</a>",
    "I ran out of beans.",
    "Eating clocks is a very time consuming process.",
    "The most website ever!",
    "A website visit a day keeps... something away!",
    "A car powered on free range chickens<br>and designed by a team of hand picked potatoes!",
    "snap back to reality",
    "In marble walls as white as milk...",
    "Just upon a ridge in Scarlet Hill...",
    "Yazoo!",
    "Computer says no.",
    "Where are we now?",
    "You say too many splash texts, I say not enough!",
    "Don't forget.",
    "Married to tea.",
    "There's a secret on the 404 page somewhere...",
    "But that's just a theory!",
    "Come back soon!",
    "--.- ..- .- -.-. -.-",
    "Bread is pain!",
    "Use bootstrap!",
    "Subscribe!",
    "I am under the water",
    "Ghoughpteighbteau tchoghs!",
    "I've been waiting for you.",
    "Welcome back!",
    "Did you miss me?",
    "YIPEE",
    "Wheatley crab!",
    "There is no among us joke.", // oh but there is
    "Don't believe everything on the internet!",
    "25th Greek island!",
    "WALL-E is the best robot.",
    "If you're seeing this, that means you exist!",
    "Windows XP was better.",
    "Where did the icon come from?",
    "12345 is a bad password!",
    "[redacted]",
    "Close range?!",
    "In the beginning the Universe was created.<br>This has made a lot of people very angry and been widely regarded as a bad move.",
    "Drink your water!",
    "There is no light, there is only duckness...",
    "DON'T LEAVE TREES FLOATING",
    "Could you pick up the beat for me please?",
    "timeout /t 10 > nul",
    "192.168.1.254",
    "For legal reasons, this is a joke.",
    "What if Dukemz isn't a duck?",
    "This sentence is false.",
    "There is a skeleton in my closet making spaghetti.",
    "D1 D1 D2 A1 G#1 G1 F1 D1 F1 G1",
    "F1 G1 C1 G1 A1 C2 B1 A1 F1 G1 C1 C1 C1 D1 D1 F1",
    "subscribe to dxl44",
    "you should play the synthwave trials by dxl44",
    "Your toes, hand em over.",
    "Now with extra duck!",
    "There was never any context to begin with.",
    '<a href="https://dukemz.github.io/SinthaliaPrototypeWeb/">Check out this old game!</a>',
    "Please ask me any questions you have!",
    "Dorime... interimo adapare dorime...",
    "Someone spilled paint to the left of this text on my desktop!",
    "Peace was always an option.",
    "Unfortunately...",
    "Dutchess_83!",
    "That's sad. I'm sad. I miss you. How did this happen?",
    "A long time ago- actually, never, (and also now)",
    "Nothing is nowhere? When? Never.",
    "Makes sense, right?",
    "That's how 'every' it gets.",
    "the sun is a deadly laser",
    ".zmekud",
    "Cats are adorable.",
    "if(variable === undefined) throw new MentalBreakdownError()",
    "Educate your friends on anti-racism!",
    "hi",
    "perhaps",
    "I'm starting to run out of things to put here...",
    "I've spent an unreasonable amount of time writing these.",
    "Please help me",
    "Lobsters inshore!",
    "Lobsters outshore!",
    ":|",
    "Absolutely NO owo's on this site.",
    "Don't uwu. $30 penalty.",
    "it's dukemzin' time",
    "and then he dukemz'd all over the place",
    "my favourite part of the dukemz movie",
    "this cat is r",
    "Please do not the cat",
    "Top 10 numbers of all time!",
    "The fog is coming.",
    "The frog is coming.",
    "It has been done.",
    "I'm going to go ahead and go have a go.",
    "You will never find out what the numbers mean.",
    "418: I'm a teapot!",
    "I'm going to invent Teascript.",
    "<br>", // you are a menace dukemz
    "gloopchita",
    "There may be birds trapped in my ribcage.",
    "Beware of robot dogs.",
    "kablinky",
    "Welcome to the world of coding! Survive while you can.",
    '<a href="https://youtu.be/-O1wszcVF1c">https://youtu.be/-O1wszcVF1c</a>',
    '<a href="https://youtu.be/-O1wszcVF1c">reads the entire tpmc wiki page in vc</a>',
    "Boiled, not fried.",
    "Pots have handles.",
    "Absolutely NO secrets whatsoever!", // yup. no secrets. i guarantee it
    "whar",
    "🛳🛳🛳",
    "Live Dukemz Reaction:",
    "Dead Dukemz Reaction:",
    "Compliant with RFC 7168!",
    "Wubba lubba dub dub!",
    "your brain tricks you into thinking",
    "What made you think this was a good idea?",
    "Are you seeing this?",
    "Hey Vsauce, Dukemz here.",
    "...or is it?",
    "...or am I?",
    "Where are your fingers?",
    "Yippee!",
    "bruh moment",
    "Momentum is the product of the mass and velocity of an object...",
    "On the shores of a purple sea.",
    "Underneath a purple sky.",
    "A splash of purple-blue water!",
    "I was the person who asked!",
    "Kraftfahrzeug-Haftpflichtversicherung!",
    "Pneumonoultramicroscopicsilicovolcanoconiosis",
    "Can a match box?",
    "Can February March?",
    "Why was 6 afraid of 7?",
    "The duck was no chicken.",
    "In the starlight.",
    "🎵",
    "We've been trying to reach you about your car's extended warranty",
    "Family friendly!",
    "Incredibly lonely!",
    "Looking for the edge of the ground.",
    "Searching for the threshold of the earth.",
    "You are our 1,000th customer! You win absolutely nothing!",
    "I'll post more soon, I promise!",
    "And as always, thanks for watching.",
    "Go to Jupiter to get shredded by the gravitational pull.",
    "I know where you live!",
    "We couldn't afford capital letters in the title.",
    "Because of budget cuts.",
    "🕶",
    "They are many colours.",
    "お前はもう死んでる",
    "何！？",
    "Quaso",
    "Cheese, versus, cheese.",
    "Don't press Ctrl + Shift + W.",
    "Press Alt + F4 to end your browsing session!",
    "(Psst... Ctrl + Shift + T re-opens a closed tab. You're welcome!)",
    "💠",
    "Click the logo for another splash without reloading!",
    "This is bromine... wait no sorry that was soy sauce.",
    "It's all good man.",
    "deezemz.",
    "If Maths didn't exist, you wouldn't be able to count the words on your English paper.",
    "ಠ_ಠ",
    "The chicken is in the oven.",
    "The pizza'll be ready any minute now, trust me...",
    "<a href='https://prominia.technobiscuit.uk'>prominia simulator</a>",
    "THERE WILL BE SHED (SHED)",
    "brrrt",
    "Today is today!",
    "HEHEHEHA",
    "GRRR",
    "That muffin is looking awfully like a hamster",
    "fr e sh a voca do",
    "✈",
    "The size of this W exceeds the tallest skyscraper.",
    "I wonder if we can reach 1000 splash messages...",
    "🤨📸",
    "There is no Easter Bunny, there is no Tooth Fairy,<br>and there is no Queen of England.",
    "You just got SVG-vectored!",
    "💌",
    "Your door was locked!",
    "Please get in the bag!",
    "Biggity Big egg the egg gets Bigger",
    "A world of my own mind's creation stands ahead...",
    "Am I code on a screen?",
    "It doesn't matter now...",
    "I wish I could fly...",
    "It's not time to say goodbye yet.",
    "Are you still awake?",
    "Aetherborne.",
    "A lullaby from an ocean beyond.",
    "There is a horizon beyond this one, and beyond the next.",
    "In a world of sound and silence.",
    "Head in the clouds.",
    "None of these make any sense.",
    "50% references, 50% dumb jokes, 100% ducks",
    "Will you be the 7168 to my 418?",
    "Disregard any logic or reason you may have.",
    "Not the original Dukemz!",
    "ok but what if",
    "Hello! I'm a helicopter!",
    "Missile inbound!",
    "Deploying flares...",
    "Do you want to be a boat instead?",
    "Yay! I am now a boat!",
    "Potato potato.",
    "...mist: The glass...",
    "Mihaly Dumitru Margareta Corneliu Leopold Blanca...",
    "...Karol Aeon Ignatius Raphael Maria Niketas A. Shilage",
    "That was so deep I could see a bunch of Adeles rolling in it.",
    "Ducks and geese: nature's amphibious assault aircraft.",
    "Firing the ducket launcher...",
    "Crisp white sheets.",
    "ROCK AND STONE",
    "We're rich!", // no monet for fortnite battle pas
    "MUSHRUM",
    "Geology rocks!",
    "Management reports foreign objects in the launch bay.",
    "potito",
    "Doomed to eternally make splash texts.",
    "ruh roh",
    "and the Portrait of what Looked Like a Large Pile of Ash",
    "Your biggest air conditioner!",
    "Not responsible for the loss of any houseplants.",
    "Go inside and touch some keyboard.",
    "Have a great day :)",
    "Take it with an entire bag of salt.",
    "Why be salty when you can be peppery?",
    "The ocean called, it wants its salt back.",
    "Try this at home!",
    "Wear eye protection!",
    "Tungsten, hydrogen, astatine: the elements of surprise.",
    "Welcome to the underground!",
    "How was the fall?",
    "A wonderful XPerience!",
    "Puffles!",
    "It looks like a hat, smells like a hat, feels like a hat.", // but it's food
    "Sell water to a fish, sell time to a clock.",
    "don't cry, i am just a fish",
    "Hey all, Dukemz here.",
    "Do you love the colour of the sky?",
    "I like your shoelaces.",
    "Stolen from the president.",
    "Someone's not in bed.",
    "Don't look for peace, it's been with you all along.",
    "If you look too hard for something, you won't find it.",
    "Don't you have anything better to do?",
    "In this world, it's dukemz or be dukemz'd.",
    "Stuck in a cycle, a repeating pattern.",
    "?ploo",
    "It certainly rains in this world.",
    "I cannot help you. I cannot even help myself.",
    "A new cycle is unfolding.",
    "At the precipice of trust.",
    "You are starving. Your game has not been saved.",
    "Ive Piblubs blast!!!",
    "books to the tune",
    "add rain to world",
    "What was he cooking?",
    "I'm a very mysterious person.",
    "Tracing the threads of gravity.",
    "I wonder how long I'll be remembered.",
    "Hopefully sticking around for a while.",
    "Too tired to sleep.",
    "break down the gates atop the railway lines",
    "The world turns its eyes to look at you.",
    "Operationally amplifying!",
    "Extraordinary until proven otherwise.",
    "🎩 HI IM THE NOT EVIL TWIN", // tophat
    "Who the hell is Steve Jobs?",
    "the birds are coming",
    "The universe is, and we are.",
    "The quiet shade, across old bark",
    "In the ancient glade, it's always dark",
    "We do not have much connection, you and I.",
    "I hope you won't mind if I think of you as a friend.",
    "This song is new to me, but I am honoured to be a part of it.",
    "Are you sure you want to remember me?",
    "Every decision is made in darkness.",
    "Whatever happens next, I do not think it is to be feared.",
    "EEYIKES! It seems we accidentally warped to... the Outer Wilds!!!",
    "Outer Wilds 2: That's Wild! Edition",
    "Please answer me.",
    "what year is it",
    "[#]",
    "Warning: Your browser doesn't support browsing.",
    "project elevator",
    "EEYIKES, how ever shall we Project this Elevatia?",
    "EEYIKES, how ever shall we Crystalline this Chaos?",
    "EEYIKES, how ever shall we Crystal this Monarchy?",
    "EEYIKES, how ever shall we Outer these Wilds?",
    "EEYIKES, how ever shall we Rain this World?",
    "EEYIKES, how ever shall I Overuse this Joke?",
    "you truly have unleashed the crystalline chaos",
    "Did you know? Yeah me neither.",
    "Or at least, that's what people call me.",
    "No, that's not actually my name.",
    "(aka Duck Nuckem)",
    '(aka "The Duke of Macaroni Zheese")',
    "What does dukemz mean anyway?",
    "It's for me to know, and for you to find out.",
    "It's pronounced \"dukemz\".",
    "65% oxygen, 19% carbon, 10% hydrogren and 6% pizza",
    "Bromine Uranium Hydrogen",
    "Oxygen Hydrogen Nobellium",
    "Tungsten, Hydrogen and Astatine: the elements of surprise",
    "Connection terminated.",
    "Busy photosynthesising!",
    "From the river to the sea!",
    "FREE PALESTINE!",
    "You are loved, remember that.",
    "Kindness is a choice you can make every day.",
    "Laugh off a downer, lighten up a frowner,<br>smile for the good, share if you could.",
    "Reality is an illusion!",
    "The universe is a hologram!",
    "Buy gold!",
    "Why invest when you can outvest?",
    "<a href='https://www.patreon.com/dukemz'>Don't give me money!</a>",
    "I have absolutely no idea what I'm doing!",
    "Bringing you useless information since forever!",
    "Walking on blue skies, looking for something I lost.",
    "the voices",
    "Because I have nothing better to do with my life.",
    "Read <a href='https://archiveofourown.org/works/50444191?view_full_work=true'>Torches and Shadows!</a>",
    "What is love?",
    "What's the difference between a bus and a coach?",
    "boingus",
    "So you found me. Congratulations. Was it worth it?",
    "This moment is yours and yours alone.",
    "I'm tired. Are you tired too?",
    "Speaking in a voice of silence.",
    "What is happiness?",
    "happiness is... sosig",
    "books to the tune",
    "shfukad",
    "have 2 save muns for colleg...",
    "cool leg",
    "yoinky sploinky",
    "whoops",
    "boop",
    "SUPER boop",
    "EVIL boop",
    "nuh uh",
    "It would be so awesome, it would be so cool",
    "It would be incredibly awkward if someone found this site and expected it to be professional.",
    "Don't worry, few people get the inside jokes here.",
    "Grah! Interloper!",
    "16 // 16 // 16",
    "giasfelfebrehber",
    "giasfclfebrehber",
    "suspicious kazoo",
    "let me drive my van into your heart",
    "kazookemz gaming",
    "TEA NOT AFRAID",
    "project elevator",
    "Multiplying strings...",
    "The three states of matter: true, false, and null",
    "undefined",
    "defined",
    "What's the lava version of wet?",
    "If ice is rock then water is lava.",
    "Did you know? Because I didn't.",
    "Did you know? 113% of statistics are made up.",
    "Did you know? 101% of statistics have a rounding error.",
    "Did you know? 22° of statistics use incorrect units.",
    "Did you know? Roughly 30-ish percent of statistics are too vague.",
    "14% of statistics aren't not disaequately unambiguated incorrectly.",
    "Running on 100% blue energy since 2024!",
    "We aim to reduce our carbon footprint to a carbon fingerprint by 2000 BC.",
    "Website changelog: Removed Herobrine.",
    "Website changelog: Added more splash texts.",
    "Website changelog: Increased FPS to 43.",
    "Website changelog: Added more issues.",
    "Website changelog: The site now supports a small amount of tomfoolery.",
    "Website changelog: Functionality is no longer supported.",
    "Website changelog: Fixed 3 bugs, added 5 more.",
    "Website changelog: Didn't change anything.",
    "Website changelog: Added changelog.",
    "Website changelog: Removed changelog.",
    "Website changelog: Removed support for Windows, added support for Doors.",
    "Changelog changelog: Changed log.",
    "Siteweb logchange: Around things shuffled.",
    "Solved the trolley problem!",
    "Aw dangit!",
    "eyyy i'm the burger man",
    "You will be boiled.",
    "One day, it will be Tuesday.",
    "Friendly-family!",
    "In the beginning, it was the beginning. But that all changed.",
    "But it all changed... when the duck nation attacked.",
    "Oh no! They are dead. Don't call again.",
    "You've reached the duck hotline. Press 1 for quack, press 2 for grapes.",
    "You've yee'd your last haw.",
    "Outpizzaing the hut since 1957!",
    "Burger King implies the existence of a Burger Queen.",
    "Dairy Queen implies the existence of a Dairy King.",
    "Toast, toaster, and toastest.",
    "beesechurger",
    "Indiana Jones and the Temple of Churger with Beese<br>(sponsored by Kurger Bing)",
    "splashtext_final_FINAL_3_FORREAL.txt",
    "wooooaahhh story of under tale",
    "Human.. I remember you're Dukemz's...",
    "ayuda por favor",
    "Washing machines live longer with Calgon!",
    "Mashing wachines live longer with Galcon!",
    "Waching mashines live longer with cow gone!",
    "Fetch, decode, execute, execute, execute, execute, execute...", // people during the french revolution
    "Reduce, reuse, rain world",
    "woaw (based based based based based)",
    "To fix the problem we need to remove its source.<br>Therefore, I propose we remove the universe.",
    "The opposite of dismantle is mantle.",
    "Mantling mainframes...",
    "why do they call it oven when you of in the cold food of out hot eat the food",
    "Coffee tastes like dirt because it has to be ground.",
    "I know we'll meet again some sunny day!",
    "m whn  rmv vwls frm th splsh txt",
    "aeiou",
    "This is the greatest plaaaaan",
    "I'm the bold action maaaaaan",
    "Error: 404 page not found",
    "Punctuation saves lives!",
    "washing machine gun",
    "maybe.",
    "Giving helpful advice since some point in the past!",
    "New leader of the Crystal Clods!",
    "typeof NaN = 'number';",
    "EEYIKES, how ever shall we delta this time?",
    "Interpolating linearly!",
    "Forgive me, maths teacher, for I have sin()ned!",
    "Based in cringe!",
    "<a href='https://dukemz.github.io/deltaLerp/index_q5.html'>Check out my game thing!</a>",
    "Have you ever?",
    "Don't look at my search history!",
    "Clicking this text does nothing!",
    "I should probably do revision instead of writing these.",
    "Me? A medal for procrastination? I'll get it later.",
    "This version of the editor doesn't support any editing functionality.",
    "Play <a href='https://store.steampowered.com/app/440310/Project_Arrhythmia/'>Project Arrhythmia!</a>",
    "<a href='https://dxl44.github.io/'>Check out DXL's website!</a>",
    "lol is like jsab",
    "Go to the beach with T flip-flops. It's only logical!",
    "they've got <a href='https://youtube.com/shorts/TYi0xofceMM'>allen wrenches gerbil feeders toilet seats electric heaters<br>trash compactors juice extractors shower rods and water metres</a>",
    "Probably a nerd!",
    "erm ACTUALLY",
    "Magenta isn't a real colour, look it up!",
    "RGB CMY HSL HSV",
    "hbdsbfshf",
    "carpet",
    "check it out i'm in a house",
    "i'm in a house-like carpet",
    "HATSUNE MIKU IS THAT YOU",
    "Fizz!",
    "Buzz!",
    "Fizzbuzz!",
    "Bequeath bequeath bequeath!",
    "meow meow meow meow meow meow meow",
    "Hello everybody my name is welcome",
    "no stop what are you doing what are you",
    "Your life is EVERYTHING! You serve ALL purpose!",
    "You should treat yourself NOW!!!",
    "Give yourself a piece of that oxygen in the ozone layer!",
    "one must imagine sisyphus happy",
    "it's ULTRAKILLING time",
    "chat are we cooked",
    "in this world it's cook or be cooked",
    "am i cooking or am i cooked",
    
    
    "If you stare at this for long enough, absolutely nothing happens!<script>window.delaySplash = setTimeout(() => { alert('Okay, I lied.') }, 20000)</script>",
    "You have 10 seconds.<script>window.delaySplash = setTimeout(() => { alert('BOO! Did I scare you?') }, 10000)</script>",
    "TACTICAL NUKE INCOMING<script>window.delaySplash = setTimeout(() => { alert('*extremely loud explosion noise*') }, 10000)</script>",
    "<span onclick='alert(`HOW DARE YOU`)'>don't you dare click me...</span>",
    "<span onclick='alert(`i lied lmao.`)'>Clicking this text does ABSOLUTELY nothing!</span>",

    
    // ewoly start
    "On a scale of 1 to 10, what's your favourite colour of the alphabet?",
    "Converting pasta to concrete since 2021!",
    "sometimes gaming.",
    "In the autumn leaves start-a falling...",
    "bn fn",
    "Ping!",
    "Pong!",
    "Loading 404 page...",
    "Rerouting engine power for biscuit production...",
    "= )",
    "OUR NEW [[soon to be old]] [upgraded!] WEBSITE!!",
    "Mail mail you mail mail and mail mail you mail mail and",
    "Was that the duck of 87?!",
    "A worthy excuse of procrastination.",
    "*breathes*",
    "Only 70% banana!",
    "wen the cold doesnt coldulate the ammonia",
    "Is water wet? Well, here's a better question: is ice icy?",
    "It's delicious. Must be flavour text.",
    "Slang for 'do you kemz?'",
    "Simultaneously too much and not enough time to use.",
    "/give @e fun_times",
    "Is cheese cheese?",
    "What if this website... is cake?",
    "This website was brought to you by...",
    "Num lock on, caps lock off, scroll lock idk.",
    "h",
    "no memes in #general",
    "no general in #memes",
    "only one finger and two toes",
    "The bugs are evolving...",
    "Concatenating integers...",
    "A+ for effort.",
    "ENABLE THE BAGEL",
    "Do not feed the pigeons.",
    "Formerly known as dukemz.",
    "v2",
    "For the fans that spin really fast.",
    "Don't judge a book by its movie.",
    "Who did the physics of a bee flying?",
    "On of th lttrs on my kyboard is brokn, snd hlp.",
    "dstgdpm10h",
    "Greetings and salutations!",
    "12 13 21 22 23 24 32 34 41 42 44", // grid
    "How many holes in a polo?",
    "Generating content... This may take a while.",
    "Nothing does not rhyme with orange.",
    "Dihydrogen monoxide is not dangerous.",
    "Hello there.", // back again
    "Each Peach Pear Plum",
    "uz.demk",
    "<a href='https://www.youtube.com/watch?v=-1oRezdQEzM'>]]]</a>",
    "Me has ungood inglish.",
    "Insectophobe's nightmare.",
    "[REDUCKTED]",
    "Please keep hands inside the cart at all times.",
    "Duke of the MZ",
    "How did we get here?",
    "Don't feed ducks bread.",
    "It's-a-me!",
    "[object Object]",
    "Now in 2D!",
    "stonks",
    "Eat your veggies!",
    "A duck walked up to the lemonade stand...",
    "<a href='https://dukemz.github.io/'>Click here for another splash!</a>",
    "Welcome to Dukemz's Pizza Emporium, how may we help you?",
    "Knock knock.",
    "Why did the duck cross the road????",
    "<a href='https://bit.ly/3EjjNW8'>CLICK HERE!!!</a>",
    "Did you know?<br>There is only one splash with the word 'deposit' in it.",
    "xnopyt",
    "camelCaseIsUsefulForSeparatingWordsInCode",
    "Take your age. Add 2. Subtract 2. That's your age.",
    "This splash has only 41 characters in it.",
    "Do I smell burning chicken?",
    "19th of August 2024 17:32:47:1026", // what
    "Don't forget.",
    "#stopusinghashtags",
    "smh forgot to capitalise dukemz.",
    "ping-pong = png(i-o)",
    "colourize",
    "colorise", // american spelling
    "dUkEmZ.",
    "return null;",
    "<a href='https://dukemz.github.io/whyareyoulookinghere'>[Hyperlink Blocked]</a>",
    "Greetings traveller, rest here for a while.",
    "3... 2... 1...",
    // "owo", // no.
    "Minced garlic!",
    "Are you ready kids?",
    "Heyo!",
    "What... cactus..?",
    "{groovy brackets}",
    "sdrawkcab",
    "For more Dukemz content!",
    "Duck? *bonk*",
    "Welcome to the Internet.",
    "2^2^2^2",
    "Coincidentally, I'm reading this too.",
    "e g g",
    "Peace, love, and ducks.",
    "You are now breathing manually.",
    "Now with even more bugs!",
    "It's not a bug, it's a feature!",
    "It's not a feature, it's a bug.",
    "Spiderduck, spiderduck, naturally has webbed feet.",
    "A group of ducks is a waddling.",
    "Chocolate can be good for you, but be careful!",
    "splash_number += 1",
    "Biscuits - dunk 'em.",
    "100% random!",
    "Still on the duck hunt.<br>(No ducks were harmed in the making of this splash text.)",
    "I'm a spring duckling and I'm having a ball!",
    "Lookie lookie it's a cookie 🍪",
    "I'm ready for a break... <br>Here it is.",
    // "Melee?!", // what
    "Travelling back in time since 2034!",
    "Freshly-baked biscuits!",
    "Computer will.",
    "Computer knows.",
    "You've been put on hold, someone will see you shortly.",
    "Hello to see you now, goodbye to see you later.",
    "How many holes in a polo?", // back again again
    "Loading the duck hivemind...",
    "Toppling the economy with seashells+ and biscuits.",
    "Surfing on a purple wave.",
    "For more definitions, see Dukemz (disambiguation).",
    "Powered by procrastination!",
    "It says gullible in the URL.",
    "Hoo sayed eye cood spel mi wheurds kourectlee?",
    "Do not avoid not never doing not bad things.",
    "The fifth element: inspect element",
    "But is it really dukemz?",
    "Definitely dukemz.",
    "Photosensitive Scissor Warning",
    "What a pretty website! I sure hope no-one breaks it...",
    "Hexagons are the Bestagons.",
    "Three is a prime example of a number.",
    "Around the world...",
    "🐟",
    "aibohphobia: fear of palindromes",
    "hippopotomonstrosesquippedaliophobia: fear of long words",
    "anatidaephobia: fear that somewhere, somehow, a duck is watching you",
    "Performing accindentations since &nbsp;&nbsp;&nbsp;&nbsp; 2018!",
    "The dot signifies nothing.",
    "console.log('splash text')",
    "Spudow!",
    "Purble",
    "Have you ever seen Dukemz and Lord Duck in the same room?",
    "The daily essentials: bread, milk, bug repellent.",
    "You can have money or duck.<br>'Duck?' Duck it is then.",
    "The Second Dukemz.",
    "yo",
    "Welcome, welcome. Welcome? Welcome!",
    "And I'll dukemz again...",
    "+++ = 6<br>--+ = 5<br>++- = ?",
    "Don't turn me into a palindrome!emordnilap a otni em nrut t'noD",
    "e  g  g",
    "What came first: the duck or the egg?",
    "Welcome to duckie village",
    "It's behind you!",
    "Yes, it really says dukemz.",
    "^ true",
    "One duck tells the truth, the other lies. <br>By asking one question, get them to make an omelette.",
    "any% glitchless",
    "~ dukemz",
    "Is it dookemz or djukemz?",
    "@everyone",
    "You've reached the duckfish hotline. Are you a duck or a fish?",
    "1% programming, 99% debugging.",
    "But what does it mean?",
    "The more splashes there are, the less likely you'll see this one. Enjoy it.",
    "Fish Gaming Wednesday",
    "12345 is a passCODE!",
    ":O",
    "A wild viewer has been spotted!",
    "Duck in the mud!",
    "Straighten your back, you shrimp!",
    "Have a nice day!",
    "Everyone asks when update but not how update.<br>Especially since I don't know how.",
    "Are these truly random?",
    "I hope you aren't repeatedly reloading the splashes...",
    "Generating good content... (this may take a while)",
    "I am doney with the funny!",
    "Turned himself into a duck, funniest stuff I've ever seen.",
    "Reminder to drink water.",
    "Hold on, just got to read an entire wiki article...",
    "dukemzn't.",
    "I only just realised one splash appears twice on the list.",
    "I live in Spain but without the s or i. 🍳",
    "0.1134",
    "Building a computer from just NAND gates.",
    "What does ¬ even mean?",
    "scown scon scun scwun scoon",
    "tl;dr: dukemz.",
    "Coding Doom in Google Spreadsheets...",
    "variable_names_should_not_be_too_long = true;",
    "I've lost ctrl, now there's no esc.",
    "You eat an egg with or without the shell?",
    "Bowl first.",
    // "Jim", // uncomment when i play the bucket game
    "It's pronounced gif!",
    "Why Do Some People Capitalise Every Word In A Sentence?",
    "but i dont want to dukemz...", // too bad, you have to
    "Can you quack the code?",
    "eggcellent",
    "These bird puns are getting reduckulous!",
    "idk tbh gg ngl gtg brb ttyl cya gn",
    "G'day mate!", // heyo
    "Unexpected item in bagging area.", 
    "Thanks for shopping at DXL's Store.",
    "You don't know me, I don't know you.<br>And I don't know what I'm doing.",
    "'This is a ducket.'<br>'dear god'",
    "Zoom out, and I'll disappear!",
    "%{(['<>oh gosh</>'])}%",
    "|these arent brackets|",
    "beep beep im asleep, i said beep beep im... zzzzz....",
    "whomst'd've'ly'yaint'ed's'y'nt'ed'ies'ses'ing'able'ric'ive'al'nt'ne'll'al'ify",
    "Is it pronounced github or jithub?",
    "There are three types of people, you have been warned.",
    "hocus pocus, everybody amogus", // i lied
    "The duck walked up with a glint in his eye.",
    "Fat-Free!",
    "~ igloo noises ~",
    "If you wish to make an apple pie from scratch, <br>you must first invent the universe.",
    "Chips and fish!",
    "It's actually 51/101 full.",
    "No ads!",
    "The universe is all buckets.",
    "One of the dukemz of all time!",
    "Congratulations! You got this splash!",
    "The good news is that there is no bad news.",
    "The bad news is that there is no good news.",
    "def pain():<br>   return 'french bread'",
    "Remember to save your workings!",
    "Make a back-up, don't lose all your files!",
    "Awaiting input...",
    "I found you.",
    "Jack and Jill went down the hill. They learnt their lesson.",
    "Did you know? There are about 73,000 different tree species!",
    "Did you know? Bread and eggs spoil faster in the fridge!",
    "Did you know? Chocolate and grapes are toxic to dogs, be careful!",
    "Did you know? Oranges are an artificial hybrid of a pomelo and a mandarin.",
    "Did you know? Iron is the most stable element in existence!",
    "Did you know? Strawberries are not berries, but pumpkins and bananas are!",
    "Did you know? The first use of OMG was in a letter to Winston Churchill!",
    "wait a minute...<script>window.delaySplash = setTimeout(() => { alert('You actually waited a minute? I'm impressed') }, 60000)</script>",
    "Let's play rock, paper, scissors!<script>window.delaySplash = setTimeout(() => { alert('I chose rock! Who won?') }, 4000)</script>",
    "Let's play rock, paper, scissors!<script>window.delaySplash = setTimeout(() => { alert('I chose paper! Who won?') }, 4000)</script>",
    "Let's play rock, paper, scissors!<script>window.delaySplash = setTimeout(() => { alert('I chose scissors! Who won?') }, 4000)</script>",
    "I TOTALLY hate sarcasm. Yep. Definitely.",
    "Indigo doesn't exist.",
    "Leave out a bowl of cream every night to stay safe frOm_ tH3 H#7|?37} .>,%",
    "DUKEMZ WHERE THE HELL ARE WE?!",
    "dankemz.",
    "It's ironic that social media makes people antisocial.",
    "Remember to wash your bones! (teeth)",
    "When we meet again... friend.",
    "I have done nothing but teleport bread for 3 days", // back back again
    "Despite everything, it's still dukemz.",
    "💛 See that heart?",  // no
    "Egg.",
    "There was a tiny piece of cheese floating in the middle of space.",
    "This text is made of water. Must be splash text.",
    "circles!",
    "Hexagons are the bestagons",
    "I have a very special splash.",
    "Still stealing shoelaces...",
    "Sphynx of black quartz, judge my vow",
    "Calculating absrop and finding semordnilaps...",
    "The note you make when you stub your toe is F#",
    "In dukemz's nest, nobody jumps for the goose.",
    "dukemz dukemz.",
    "(probably)",
    "Do not look up the name of the spinny loady thingy.",
    "I am a building",
    "syzygy has good synergy",
    "Our moon is called Luna!",
    "There's more hydrogen atoms in a molecule of water <br>than there are stars in the entire solar system!",
    "Dance like a crab on a beach!",
    "<a href='https://www.youtube.com/watch?v=lknzALc0NeA'>dstgdpm10h</a>",
    "the roomba has no natural predators...",
    "[ERROR %2763%: 'Missing splash text']",
    ".-_-.",
    "If you're in the eye of the storm, hope it doesn't blink...",
    "Defenestration: the act of being thrown out of a window.",
    "'Road works ahead' signs only appear when it doesn't",
    "The chicken came first, because it was said first.",
    "You don't know who came up with this splash.", // well now you do
    "Apple devices run on apple juice.",
    "I feel shattered, it's such a pane.",
    "This is the 828th added splash. Woah.",
    "nuh uh",
    "wdym nuh uh",
    "Soon™",
    "Left. Right. Block.", // ill be surprised if you get this reference
    "the oven is in the chicken",
    "\"string\"",
    "73 78 84", 
    "01100010 01101111 01101111 01101100", // work it out without translation
    "Octopi have an amazing byte",
    "Please do not the cat",
    "Use Firefox!",
    "Uninstall McAfee... please...",
    "Living in the present since today!",
    "The default object is sightly, smelly, tasty, noisy, and touchy.",
    "#524742 is the RGB of RGB",
    "This is a splash. Or is it?", // vsauce music
    "Out now.",
    "You found me!",
    "And finally, in finality...",
    // ewoly end (epic)
    "This is almost the last splash text. Almost, but not quite."
]
splashes.push(`There are ${splashes.length + 2} splash texts. Isn't that weird?`);
splashes.push(`The chance of you seeing this message is 1 in ${splashes.length + 1}.`);
window.splashReloadCount = 0;
// in the future - put date specific splashes here

// everything below here is tb's stuff

// https://francoisromain.medium.com/smooth-a-svg-path-with-cubic-bezier-curves-e37b49d46c74
const line = (pointA, pointB) => {
    const lengthX = pointB[0] - pointA[0]
    const lengthY = pointB[1] - pointA[1]
    return {
      length: Math.sqrt(Math.pow(lengthX, 2) + Math.pow(lengthY, 2)),
      angle: Math.atan2(lengthY, lengthX)
    }
}

const controlPoint = (current, previous, next, reverse) => {
    // When 'current' is the first or last point of the array
    // 'previous' or 'next' don't exist.
    // Replace with 'current'
    const p = previous || current
    const n = next || current
    // The smoothing ratio
    const smoothing = 0.2
    // Properties of the opposed-line
    const o = line(p, n)
    // If is end-control-point, add PI to the angle to go backward
    const angle = o.angle + (reverse ? Math.PI : 0)
    const length = o.length * smoothing
    // The control point position is relative to the current point
    const x = current[0] + Math.cos(angle) * length
    const y = current[1] + Math.sin(angle) * length
    return [x, y]
}

const bezierCommand = (point, i, a) => {
    // start control point
    const [cpsX, cpsY] = controlPoint(a[i - 1], a[i - 2], point)
    // end control point
    const [cpeX, cpeY] = controlPoint(point, a[i - 1], a[i + 1], true)
    return `C ${cpsX},${cpsY} ${cpeX},${cpeY} ${point[0]},${point[1]}`
}

const svgPath = (points, command) => {
    // build the d attributes by looping over the points
    const d = points.reduce((acc, point, i, a) => i === 0
      // if first point
      ? `M ${point[0]},${point[1]}`
      // else
      : `${acc} ${command(point, i, a)}`
    , '')
    return d;
}


//

const recalcShape = () => {
    // lol sorry for putting this here - duck
    clearTimeout(window.delaySplash);
    const sploosh = splashes[Math.floor(Math.random()*splashes.length)];
    
    // biscuit to the rescue with jquery (hopefully)
    if ($("#randomSplash").length) $("#randomSplash").html(sploosh);
    //let splText = document.getElementById("randomSplash")?.innerHTML;
    //console.log(splText)
    //if(splText !== undefined) splText = sploosh;

    // april fools
    /*
    window.splashReloadCount += 1;
    if(window.splashReloadCount < 5 && ($("#randomSplash").length)) {
        $("#randomSplash").html("april fools lol");
    }*/
    
    $(".shape-thing").empty();
    let points = [[0, 0]];
    for (let y = 0; y < $(document).height() * 6; y += 200) {
        points.push([330 + (60 - (120 * (Math.random()))), y]);
    }

    let path = "";

    for (let i = 0; i < points.length; i++) {
        path += `L ${points[i][0]} ${points[i][1]} `;
    }

    path += `L 0 ${points[points.length - 1][1]} Z`

    $(".background").css("height", `${$(document).height()}px`)

    $(".shape-thing").append($(`
    <svg viewBox="0 0 500 ${points[points.length - 1][1]}" xmlns="http://www.w3.org/2000/svg">
        <linearGradient gradientUnits="userSpaceOnUse" x1="148.964" y1="44.905" x2="148.964" y2="492.678" id="gradient-0" gradientTransform="matrix(0.918522, 0.395369, -0.408856, 0.949858, 71.08396, -91.186193)" spreadMethod="pad">
            <stop offset="0" style="stop-color: rgb(11, 184, 253);"/>
            <stop offset="1" style="stop-color: rgb(90, 66, 236);"/>
        </linearGradient>
        <path d="${svgPath(points, bezierCommand)} L 0 ${points[points.length - 1][1]} Z" fill="url(#gradient-0)" />
    </svg>
    `));
}

$(window).resize(_.debounce(recalcShape, 200));

console.log("hi lol\nthere's no secrets here either, sorry");
